spring.application.name=review-system
spring.data.elasticsearch.cluster-nodes=localhost:9200
spring.data.elasticsearch.cluster-name=docker-cluster
spring.elasticsearch.rest.uris=http://localhost:9200
elasticsearch.host=localhost
elasticsearch.port=9200

server.port=8082

# Kafka properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic.movie-events=bookMyShow-events-topic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=review-group
spring.kafka.consumer.auto-offset-reset=earliest
